# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_jobexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexperience',
            name='current_job',
            field=models.BooleanField(default=False),
        ),
    ]
