# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 03:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_jobexperience_current_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexperience',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_experience', to=settings.AUTH_USER_MODEL),
        ),
    ]
